= Monodrone-CI
ifdef::env-github[]
:warning-caption: :warning:
endif::[]

== Installation

. Start link:https://ngrok.com[`ngrok`] on port 8080
+
[source, shell]
----
ngrok http 8080
----

. Export the `NGROK_HOST` environment variable
+
[source, shell]
----
export NGROK_HOST=<ngrok-host>
# e.g. export NGROK_HOST=1ab23c45.ngrok.io
----

. Create a link:https://github.com/settings/applications/new[GitHub OAuth2 application]
+
* The URL should be: `https://<ngrok-host>`
* The Callback URL should be: `https://<ngrok-host>/login`

. Copy the `.env_vars.example` file
+
[source, shell]
----
cp .env_vars.example .env_vars
----

. Customize the `.env_vars` file:
+
* Replace the `DRONE_GITHUB_CLIENT_ID` and `DRONE_GITHUB_CLIENT_SECRET` variables based on the values generated by GitHub when you created your OAuth2 application
* Create a link:https://github.com/settings/tokens/new[Personal GitHub Access-Token] with `repo` access
* Set the `DRONE_RPC_SECRET` and `DRONE_YAML_SECRET` to whatever you want

.  Start `docker-compose`
+
[source, shell]
----
docker-compose -f drone-compose.yaml up
----
+
WARNING: When the application starts or when it fetches repositories, a lot of HTTP connection are opened. This can lead to ngrok errors saying: "too much connection opened in the last minute". Just wait a minute and you are good  to go.
